name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - uses: snok/install-poetry@v1

      - name: Install dependencies
        run: poetry install

      - name: Run tests with coverage
        run: poetry run pytest --cov --cov-report=xml

      - name: Run security checks
        run: |
          poetry run safety check
          poetry run bandit -r ft_place_bot/

      - name: Type check
        run: poetry run mypy ft_place_bot/

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          fail_ci_if_error: true
